[settings]
experimental = true
pin = true
install_before = "3d"
lockfile = true

[tools]
"aqua:dprint/dprint" = "0.54.0"
"aqua:jdx/hk" = "1.48.0"
"core:java" = "zulu-25.34.17.0"
"core:python" = "3.14.5"
"core:rust" = { version = "1.96.0", profile = "minimal", components = "rustfmt,clippy", targets = "wasm32-unknown-unknown" }
"aqua:sharkdp/hyperfine" = "1.20.0"
"aqua:google/google-java-format" = "1.35.0"
"aqua:pnpm/pnpm" = "11.9.0"
"core:node" = "24.18.0"

[deps.pnpm]
auto = true

[deps.imports]
auto = true
sources = ["tools/import/import.py"]
outputs = ["tools/import/.imports"]
run = "python tools/import/import.py"

[tasks.check]
run = "hk check --all"

[tasks.test]
usage = 'flag "--update" help="Update insta snapshots"'
run = 'INSTA_UPDATE="$([ "${usage_update:-false}" = "true" ] && printf always || printf no)" cargo test --workspace'

[tasks.build]
depends = ["build:jolt", "build:dprint-plugin"]

[tasks."build:jolt"]
usage = '''
flag "--mode <mode>" help="Cargo build mode" {
  choices "debug" "release"
  default "debug"
}
'''
run = '''
case "${usage_mode?}" in
  debug) cargo build --package jolt_fmt_cli ;;
  release) cargo build --package jolt_fmt_cli --release ;;
esac
'''

[tasks."jolt"]
raw_args = true
run = "cargo run -p jolt_fmt_cli --"

[tasks."build:dprint-plugin"]
usage = '''
flag "--mode <mode>" help="Cargo build mode" {
  choices "debug" "release"
  default "debug"
}
'''
run = '''
case "${usage_mode?}" in
  debug) cargo build --target wasm32-unknown-unknown --package jolt_fmt_dprint --features wasm ;;
  release) cargo build --release --target wasm32-unknown-unknown --package jolt_fmt_dprint --features wasm ;;
esac
'''

[tasks."dprint-with-jolt"]
depends = ["build:dprint-plugin"]
raw_args = true
run = "dprint --plugins=\"$PWD/target/wasm32-unknown-unknown/debug/jolt_fmt_dprint.wasm\""

[tasks.benchmark]
usage = '''
arg "[tools]" help="Benchmark tools" var=#true {
  choices "jolt" "dprint-jolt" "google-java-format" "prettier-java" "all"
}
'''
depends = [
  { task = "build:jolt", args = ["--mode", "release"] },
  { task = "build:dprint-plugin", args = ["--mode", "release"] },
]
run = 'python tools/bench/bench.py ${usage_tools:-}'

[tasks.fix]
run = "hk fix --all"

[hooks]
postinstall = ["hk install --mise"]
