use jolt_syntax::RawSyntaxKind;
use num_enum::{IntoPrimitive, TryFromPrimitive};

/// A Kotlin token or syntax node kind.
///
/// This enum is language-wide: lexer tokens and parser-created CST nodes share
/// the same kind space, while the syntax tree stores whether an element is a
/// token or node structurally. The token inventory follows the Kotlin
/// compiler's `KtTokens` split between hard keywords, soft keywords, modifier
/// keywords, string-template tokens, and punctuation/operator tokens.
#[repr(u16)]
#[derive(Clone, Copy, Debug, Eq, Hash, IntoPrimitive, PartialEq, TryFromPrimitive)]
#[allow(clippy::enum_variant_names)]
pub enum KotlinSyntaxKind {
    /// End-of-file marker.
    Eof,
    /// Unknown token emitted for lexer recovery.
    Unknown,
    /// Reserved token spelling, such as `...`.
    Reserved,

    // Literals and identifiers.
    Identifier,
    FieldIdentifier,
    IntegerLiteral,
    FloatLiteral,
    CharacterLiteral,

    // String-template tokens.
    InterpolationPrefix,
    OpenQuote,
    ClosingQuote,
    RegularStringPart,
    EscapeSequence,
    ShortTemplateEntryStart,
    LongTemplateEntryStart,
    LongTemplateEntryEnd,
    DanglingNewline,

    // Hard keywords.
    PackageKw,
    AsKw,
    TypeAliasKw,
    ClassKw,
    ThisKw,
    SuperKw,
    ValKw,
    VarKw,
    FunKw,
    ForKw,
    NullKw,
    TrueKw,
    FalseKw,
    IsKw,
    InKw,
    ThrowKw,
    ReturnKw,
    BreakKw,
    ContinueKw,
    ObjectKw,
    IfKw,
    TryKw,
    ElseKw,
    WhileKw,
    DoKw,
    WhenKw,
    InterfaceKw,
    TypeOfKw,
    AsSafe,

    // Soft keywords.
    AllKw,
    FileKw,
    FieldKw,
    PropertyKw,
    ReceiverKw,
    ParamKw,
    SetParamKw,
    DelegateKw,
    ImportKw,
    WhereKw,
    ByKw,
    GetKw,
    SetKw,
    ConstructorKw,
    InitKw,
    ContextKw,
    CatchKw,
    DynamicKw,
    FinallyKw,

    // Modifier keywords.
    AbstractKw,
    EnumKw,
    ContractKw,
    OpenKw,
    InnerKw,
    OverrideKw,
    PrivateKw,
    PublicKw,
    InternalKw,
    ProtectedKw,
    OutKw,
    VarargKw,
    ReifiedKw,
    CompanionKw,
    SealedKw,
    FinalKw,
    LateinitKw,
    DataKw,
    ValueKw,
    InlineKw,
    NoinlineKw,
    TailrecKw,
    ExternalKw,
    AnnotationKw,
    CrossinlineKw,
    OperatorKw,
    InfixKw,
    ConstKw,
    SuspendKw,
    ExpectKw,
    ActualKw,

    // Delimiters and punctuation.
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    LParen,
    RParen,
    Dot,
    Question,
    ColonColon,
    Colon,
    Semicolon,
    DoubleSemicolon,
    Range,
    RangeUntil,
    Assign,
    Hash,
    At,
    Comma,
    EolOrSemicolon,

    // Operators.
    PlusPlus,
    MinusMinus,
    Star,
    Plus,
    Minus,
    Bang,
    Slash,
    Percent,
    Lt,
    Gt,
    LtEq,
    GtEq,
    EqEqEq,
    Arrow,
    DoubleArrow,
    BangEqEqEq,
    EqEq,
    BangEq,
    BangBang,
    AndAnd,
    Amp,
    OrOr,
    SafeAccess,
    Elvis,
    StarEq,
    SlashEq,
    PercentEq,
    PlusEq,
    MinusEq,
    NotIn,
    NotIs,

    // Nodes.
    ErrorNode,
    KotlinFile,
    PackageHeader,
    ImportList,
    ImportDirective,
    ImportAlias,
    ModifierList,
    Annotation,
    AnnotationUseSiteTarget,
    AnnotationArgumentList,
    ValueArgumentList,
    ValueArgument,
    Name,
    QualifiedName,
    CallableName,
    TypeArgumentList,
    TypeArgument,
    ClassDeclaration,
    InterfaceDeclaration,
    ObjectDeclaration,
    CompanionObject,
    EnumEntry,
    ClassBody,
    ClassMemberDeclaration,
    PrimaryConstructor,
    SecondaryConstructor,
    ConstructorDelegationCall,
    InitializerBlock,
    FunctionDeclaration,
    PropertyDeclaration,
    PropertyAccessor,
    ExplicitBackingField,
    TypeAliasDeclaration,
    TypeParameterList,
    TypeParameter,
    TypeConstraintList,
    TypeConstraint,
    ContextParameterClause,
    ContextParameter,
    DelegationSpecifierList,
    DelegationSpecifier,
    UserType,
    NullableType,
    FunctionType,
    ContextFunctionType,
    ReceiverType,
    ParenthesizedType,
    FunctionTypeParameter,
    DefinitelyNonNullableType,
    TypeProjection,
    TypeProjectionList,
    Block,
    Statement,
    ExpressionStatement,
    LocalDeclaration,
    AssignmentExpression,
    BinaryExpression,
    UnaryExpression,
    PostfixExpression,
    CallExpression,
    IndexExpression,
    NavigationExpression,
    CallableReferenceExpression,
    LiteralExpression,
    StringTemplateExpression,
    StringTemplateEntry,
    NameExpression,
    ThisExpression,
    SuperExpression,
    ParenthesizedExpression,
    AnnotatedExpression,
    IfExpression,
    WhenExpression,
    WhenSubject,
    WhenEntry,
    WhenCondition,
    WhenGuard,
    TryExpression,
    CatchClause,
    FinallyClause,
    LoopExpression,
    ForStatement,
    WhileStatement,
    DoWhileStatement,
    JumpExpression,
    ThrowExpression,
    LambdaExpression,
    LambdaParameterList,
    LambdaParameter,
    AnonymousFunctionExpression,
    ObjectExpression,
    CollectionLiteralExpression,
    DestructuringDeclaration,
    DestructuringEntry,
    ValueParameterList,
    ValueParameter,
    TypeReference,
}

impl KotlinSyntaxKind {
    /// Converts this kind into the raw representation used by shared syntax data.
    #[must_use]
    pub(crate) fn to_raw(self) -> RawSyntaxKind {
        RawSyntaxKind::new(u16::from(self))
    }

    /// Converts a raw kind back into a Kotlin syntax kind.
    #[must_use]
    pub(crate) fn from_raw(raw: RawSyntaxKind) -> Option<Self> {
        Self::try_from(raw.get()).ok()
    }
}
